#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x

JAVA_VERSION="1.8.0_20"
JETTY_VERSION="9.2.3.v20140905"
MAVEN_VERSION="3.2.3"

export M2=$OPENSHIFT_DATA_DIR/apache-maven-${MAVEN_VERSION}/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk${JAVA_VERSION}
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd ${OPENSHIFT_DATA_DIR}jetty

if [ -L webapps ]; then
  rm webapps
else
  rm -rf webapps
fi

ln -s ${OPENSHIFT_REPO_DIR}deployments webapps

CMD="java -Xms384m -Xmx412m -jar start.jar -Djetty.host=$OPENSHIFT_DIY_IP -Djetty.port=$OPENSHIFT_DIY_PORT --exec"

nohup $CMD > $OPENSHIFT_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid
